title = "K.Y"
baseURL = "https://ttchengcheng.github.io/blog"
theme = "maupassant-hugo"

# 语言
languageCode = "zh-CN"
defaultContentLanguage = "zh"
enableEmoji = true
hasCJKLanguage = true

[author]
    name = "ttchengcheng"

[params]
  author = "ttchengcheng"
  subtitle = "dev & share"
  keywords = "golang,typescript,electron,c++,javascript"
  description = "dev & share"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"